[package]
name = "bitsync-frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console_error_panic_hook = "0.1.7"
console_log = { version = "1.0.0", features = ["color"] }
leptos = { version = "0.6.3", features = ["csr", "tracing"] }
tracing = { version = "0.1.40", features = ["log"] }
