[package]
name = "bit_sync"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.2"
dotenv = "0.15.0"
eyre = "0.6.9"
serde = { version = "1.0.193", features = ["derive"] }
serde-env = "0.1.1"
sqlx = { version = "0.7.3", features = ["runtime-tokio-rustls", "time", "uuid", "postgres"] }
time = { version = "0.3.30", features = ["serde-human-readable"] }
tokio = { version = "1.34.0", features = ["full"] }
tower = { version = "0.4.13", features = ["limit"] }
tower-http = { version = "0.5.0", features = ["trace"] }
tracing = "0.1.40"
uuid = { version = "1.6.1", features = ["serde"] }
